name = "mosaic"
main = "src/worker.js"
compatibility_date = "2025-09-01"
workers_dev = true

[assets]
directory = "public"

[[d1_databases]]
binding = "DB"
database_name = "mosaic-db"
database_id = "72e82aa8-e85d-4adf-82b3-dc84faa275b4"

[vars]
GOOGLE_CLIENT_ID = ""
ADMIN_EMAILS = "ozoz76747@gmail.com"
